---
- name: = = = Install Nginx = = =
  hosts: NGINX

  tasks:
    - name: = = = Ensure Nginx ist latest = = =
      apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes

    - name: = = = Create flask config file for Nginx = = =
      template:
        src: ./template/nginx_conf.j2
        dest: /etc/nginx/conf.d/flaskapp.conf
      become: yes

    - name: = = = Reload Nginx = = =
      service:
        name: nginx
        state: reloaded
      become: yes

